import { useState } from "react";
import NotesViewer from "../components/NotesViewer";

export default function Generator() {
  const [topic, setTopic] = useState("");

  // ✅ levels for all (School + BTech + GATE)
  const [level, setLevel] = useState("Class 6-8 (School)");

  // ✅ length
  const [length, setLength] = useState("Medium");

  // ✅ language
  const [language, setLanguage] = useState("English");

  const [notes, setNotes] = useState("");
  const [loading, setLoading] = useState(false);

  // ✅ High-quality structured template (abhi mock, Step 4 me AI real banega)
  function buildProNotes({ topic, level, length, language }) {
    const depth =
      length === "Short"
        ? "concise"
        : length === "Medium"
        ? "detailed"
        : "very detailed";

    const target =
      level.includes("Class 6-8")
        ? "simple school-level with easy words"
        : level.includes("Class 9-10")
        ? "board-level with clear definitions and examples"
        : level.includes("Class 11-12")
        ? "senior-secondary level with deeper concepts and examples"
        : level.includes("BTech")
        ? "college-level with technical depth + real-world relevance"
        : "GATE-level with exam-focused points, traps, and revision bullets";

    const langLine =
      language === "Hinglish"
        ? "Write in Hinglish (easy Hindi + English mix)."
        : "Write in clear English.";

    return `# ${topic} — ${level}

**Quality Target:** ${depth} notes, ${target}  
**Language:** ${language}. (${langLine})

---

## 1) Definition (Exam-ready)
- **${topic}**: (Definition will be generated by AI in Step 4)
- **Why important?** (1–2 lines)

---

## 2) Core Concepts (Step-by-step)
1. **Concept 1:** Explanation + why it matters  
2. **Concept 2:** Explanation + key point  
3. **Concept 3:** Explanation + connection to syllabus / real world  

---

## 3) Key Terms / Keywords
- Term 1: meaning  
- Term 2: meaning  
- Term 3: meaning  

---

## 4) Examples (Easy → Advanced)
### Easy Example
- (simple example)

### Practical Example
- (real-life / application)

### If BTech/GATE (extra)
- (numerical / typical exam pattern idea)

---

## 5) Common Mistakes / Traps (Important)
- Mistake 1  
- Mistake 2  
- Mistake 3  

---

## 6) Quick Revision (5 bullets)
- Bullet 1  
- Bullet 2  
- Bullet 3  
- Bullet 4  
- Bullet 5  

---

## 7) Mini Quiz (5 Questions)
1) Q1  
2) Q2  
3) Q3  
4) Q4  
5) Q5  

> ✅ Step 4 me isi exact format me REAL AI content aayega (top-quality).`;
  }

  const handleGenerate = () => {
    const t = topic.trim();
    if (!t) return alert("Please enter a topic");

    setLoading(true);

    const pro = buildProNotes({
      topic: t,
      level,
      length,
      language,
    });

    setTimeout(() => {
      setNotes(pro);
      setLoading(false);
    }, 600);
  };

  return (
    <div style={{ maxWidth: 750, margin: "40px auto", fontFamily: "Arial" }}>
      <h1>AI Notes Generator</h1>

      <div style={{ display: "grid", gap: 10 }}>
        <input
          type="text"
          placeholder="Enter topic (e.g., DBMS Normalization / OS Deadlock)"
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          style={{ width: "100%", padding: 10 }}
        />

        {/* ✅ Levels */}
        <select
          value={level}
          onChange={(e) => setLevel(e.target.value)}
          style={{ width: "100%", padding: 10 }}
        >
          <option>Class 6-8 (School)</option>
          <option>Class 9-10 (Board)</option>
          <option>Class 11-12 (Board)</option>
          <option>BTech (College)</option>
          <option>GATE (Exam)</option>
        </select>

        {/* ✅ Length */}
        <select
          value={length}
          onChange={(e) => setLength(e.target.value)}
          style={{ width: "100%", padding: 10 }}
        >
          <option>Short</option>
          <option>Medium</option>
          <option>Long</option>
        </select>

        {/* ✅ Language */}
        <select
          value={language}
          onChange={(e) => setLanguage(e.target.value)}
          style={{ width: "100%", padding: 10 }}
        >
          <option>English</option>
          <option>Hinglish</option>
        </select>

        <button
          onClick={handleGenerate}
          disabled={loading}
          style={{
            width: "100%",
            padding: 12,
            background: loading ? "#444" : "black",
            color: "white",
            border: "none",
            cursor: loading ? "not-allowed" : "pointer",
          }}
        >
          {loading ? "Generating..." : "Generate Notes"}
        </button>
      </div>
          <NotesViewer
  notes={notes}
  onCopy={async () => {
    await navigator.clipboard.writeText(notes);
    alert("Copied ✅");
  }}
  onClear={() => setNotes("")}
/>
    </div>
  );
}